### ISSUE TITLE
Twig 3 composer install / update - Problem

### ISSUE THREAD

**Issue by febrez** [kint-php/kint-twig#1]
Hello,

Encountered an issue while trying to update to Twig v3

` Problem 1
    - kint-php/kint-twig 2.0 requires twig/twig ^1.34 || ^2.4`

**Comment by jnvsor** [comment]
I'm not sure if it's currently compatible with v3, I'll probably want to release a new version soon anyway so I'll get to this soon (Hopefully)

**Comment by jnvsor** [comment]
@febrez Sorry it took so long.

New major version out with slight changes to functionality and support for twig 3. PHP 5 support is dropped since twig 2 already requires php 7.
